kind: pipeline
name: default

steps:
- name: test
  image: python 3.7
  commands:
  - pip install -r requirements.txt
  - python test_secure.py
  - pip install -U pytest pytest-cov coverage codecov sphinx --use-mirrors
  - py.test --cov=./
  - pip install -r requirements.txt
  - python test_secure.py
