kind: pipeline
name: python-2

steps:
- name: test
  image: python:2
  commands:
  - pip install -r requirements.txt
  - python test_secure.py
  - pip install -U pytest pytest-cov coverage codecov sphinx --use-mirrors
  - python py.test --cov=./

