kind: pipeline
name: python-3-4

steps:
- name: test
  image: python:3.4
  commands:
  - pip install -r requirements.txt
  - python test_secure.py
  - pip install -U pytest pytest-cov coverage codecov sphinx --use-mirrors
  - python py.test --cov=./
---
ind: pipeline
name: python-3-7

steps:
- name: test
  image: python:3.7
  commands:
  - pip install -r requirements.txt
  - python test_secure.py
  - pip install -U pytest pytest-cov coverage codecov sphinx --use-mirrors
  - python py.test --cov=./

