
dist:  xenial  #enables >=3.7
language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install pytest-cov
# command to run tests...cov for coveralls
deploy:
  provider: script
  script: uft_vb.vbs
script:
  - pytest --cov | coveralls
# sends to coveralls
after_success:
  - coveralls
  - git add -A
deploy:
  provider: pypi
  skip_cleanup: true
  user: lmasters
  password: Starstar49
  on:
    python: 3.7
  skip_existing: true
