dist:  xenial  #enables >=3.7
language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests...cov for coveralls
script:
  - pytest --cov=YourModule/
# sends to coveralls
after_success:
  - coveralls