language: python
python:
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest
  - codecov --token=f0beab50-863e-49cc-9f25-c505b4a2cd2e